vich_uploader:
  db_driver: orm

  mappings:
    marche_unique_files:
      uri_prefix: "%app.path.marche_unique_files%"
      upload_destination: "%kernel.project_dir%/public%app.path.marche_unique_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    bon_commande_files:
      uri_prefix: "%app.path.bon_commande_files%"
      upload_destination: "%kernel.project_dir%/public%app.path.bon_commande_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    contrat_files:
      uri_prefix: "%app.path.contrat_files%"
      upload_destination: "%kernel.project_dir%/public%app.path.contrat_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    recette_files:
      uri_prefix: "%app.path.recette_files%"
      upload_destination: "%kernel.project_dir%/public%app.path.recette_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    depense_files:
      uri_prefix: "%app.path.depense_files%"
      upload_destination: "%kernel.project_dir%/public%app.path.depense_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer